### ISSUE TITLE
The Gas charges present the opposite result to the actual bridge destination and result

### ISSUE THREAD

**Issue by ozingi** [lifinance/sdk#139]
The display result of the Gas fee in the cross-chain process is inconsistent with the actual result. It is possible that the Gas fee result of fromChainId->toChainId is incorrectly changed to the Gas fee result of toChainId->fromChainId when the back-end returns
jumper：
![图片](https://user-images.githubusercontent.com/23213458/236798226-eeb513e2-c2c0-4262-9ded-f09a7a97dce4.png)
![图片](https://user-images.githubusercontent.com/23213458/236798303-38ff2351-32a5-489c-8d27-f8071be6514b.png)
![图片](https://user-images.githubusercontent.com/23213458/236799019-c6c6e485-4275-4b69-93db-bc3216da72e8.png)

Actual situation：
![图片](https://user-images.githubusercontent.com/23213458/236796877-20ab65b0-c674-463f-8b96-bf32a7b0da6f.png)
![图片](https://user-images.githubusercontent.com/23213458/236796988-065aa563-2df1-4da7-96de-f8db5615ddee.png)

**Comment by chybisov** [comment]
@ozingi looks like a Hop UI issue or a misinterpretation of what they are trying to show. When you try to send something from Ethereum to Optimism you need to pay gas on Ethereum to sign the source transaction, and on Jumper, in your example, we show how much it would cost you. The same applies to the transfer from Optimism to Ethereum. Hop UI shows the destination transaction cost, not the source.

<img width="640" alt="image" src="https://user-images.githubusercontent.com/18644653/237016060-e5207168-bc13-4808-bc96-5fac25d279db.png">

**Comment by ozingi** [comment]
It's true that jumper is right, maybe hop wants the user to try to get to L2
