### ISSUE TITLE
Feature Request : Flag to hide 0 balances in getTokenBalances

### ISSUE THREAD

**Issue by SMLaursen** [lifinance/sdk#145]
Would be nice having the option to hide 0 balances from the `getTokenBalancesForChains` and `getTokenBalances` responses

**Comment by chybisov** [comment]
We will add this to our TODO 😄

**Comment by chybisov** [comment]
The SDK v3 has been released. Please see the documentation here https://docs.li.fi/integrate-li.fi-sdk/li.fi-sdk-overview
