### ISSUE TITLE
CELO Support dropped?

### ISSUE THREAD

**Issue by SMLaursen** [lifinance/sdk#161]
I noticed that as of this week'ish, querying for Celo tokens (`https://li.quest/v1/tokens?chains=42220`) returns nothing `{"tokens":{}}`.

Querying `https://li.quest/v1/chains` indicates that Celo is no longer supported. 

Is Celo support dropped intentionally or is it mistake?

**Comment by SMLaursen** [comment]
Ah I see, makes sense. Thanks 😊

I was relying on aforementioned endpoints to retrieve balances across chains. Do you plan re-enable retrieving token-balances despite not supporting bridging? Alternatively, do you plan to integrate with other Celo bridges?

**Comment by melianessa** [comment]
Yes, we have plans to enable CELO in CelerIM bridge.
Also, you can retrieve token balances even if we don't provide you with chain information from the /chains endpoint. You just need to pass the correct parameters to the `getBalance` method.

**Comment by SMLaursen** [comment]
Thanks alot, I'm also using your endpoints (`https://li.quest/v1/tokens`) for maintaining/tracking ERC20 addresses ;)
