### ISSUE TITLE
Testnet Endpoint unstable?

### ISSUE THREAD

**Issue by sunela-tr** [lifinance/sdk#168]
As per your docs, I'm using `'https://staging.li.quest/v1/'` to retrieve testnet balances. This worked well until ~1week ago, from which point in time I no longer received Goerli or Mumbai results. Furthermore, from this point on a lot of "weird" Ether balances are returned (YYB, CHE, IGNISLITE, PNS, YJM, HL, DAPP, CEHH)

**Comment by SMLaursen** [comment]
Fyi; As of today, I'm also seeing the (YYB, CHE, IGNISLITE, PNS, YJM, HL, DAPP, CEHH) Tokens on your Mainnet endpoint ☺️

**Comment by chybisov** [comment]
Thanks for reporting the issue, we will check this out 👀

**Comment by chybisov** [comment]
Weird tokens should be gone now 🙂

**Comment by sunela-tr** [comment]
I'm still seeing IGNISLITE and PSYOP which I believe are scam-coins - don't know if you'll moderate such or not

**Comment by sunela-tr** [comment]
Also, Goerli (Native) and Mumbai (Native) are still missing;
![image](https://github.com/lifinance/sdk/assets/88385740/7c003972-4468-4fd4-966f-b8dc8ffed95c)

**Comment by chybisov** [comment]
@sunela-tr We released quite some updates to our token service, so things should get better now 🙂 Also, please reach out to our [discord](https://discord.com/channels/849912621360218112/1108511354253475872)/[telegram](https://t.me/lifidevs) support for any API-related questions. Thank you! ❤️
