### ISSUE TITLE
Adding `Speed Up` or `Cancel Transaction` to the `RouteExecutionManager` for stuck transaction

### ISSUE THREAD

**Issue by digital-flowers** [lifinance/sdk#175]
Hi there, 
I am Fareed from Quantum Wallet,
While testing I run into a transaction that is stuck on polygon since 2 days:

<img width="200" alt="Screenshot 2024-01-08 at 10 42 13 PM" src="https://github.com/lifinance/sdk/assets/5216291/3b8f65b4-917e-4583-8df1-71244093924c">

the transaction hash is: https://polygonscan.com/tx/0x77b1f103a3b876234188e3f1dea337753f9f3a08eb60fb19753c6e3507f113b5

Within our wallet we added the retry transaction which is calling `RouteExecutionManager.executeRoute` which is working fine for failed transactions, but we are trying to add "Cancel Transaction" or "Speed Up Transaction" for stuck transaction similar to our native transactions like MetaMask, We were wondering if this feature exists in the LI.FI SDK or how can we achive that without creating conflict with your SDK?

thanks for the help :)

**Comment by chybisov** [comment]
@digital-flowers Widget and SDK support and handle speeding up and canceling transactions through wallet mechanics and we track replaced transactions. There are no plans to add these buttons to the widget until the v3 release, maybe after 🙂

**Comment by digital-flowers** [comment]
@chybisov thank you for clarification we will try handle these from our side :)
