### ISSUE TITLE
ERROR: 'No available quotes for the requested transfer' when trying to request a bridge quote

### ISSUE THREAD

**Issue by b0gdaniy** [lifinance/sdk#178]
I need to bridge SMT token from the Polygon to the Mainnet, using this request 
`https://li.quest/v1/quote?fromChain=137&toChain=1&fromToken=SMT&toToken=SMT&fromAddress=0x5c573e7eE69926B79Be8283E4c421Ccca288bC06&toAddress=0x1A2356D54aEEad105f203a5c51a6307Ec100494e&fromAmount=100`

To check the correctness of the request, I used https://apidocs.li.fi/reference/get_quote and here response was **200**:
<img width="491" alt="screenshot" src="https://github.com/lifinance/sdk/assets/57547705/46a11a14-2bc2-4da0-a82e-8a55ee7075dc">
but when I tried to make this request on my own, it threw this error: 
```
data: {
      message: 'No available quotes for the requested transfer',
      code: 1002,
      errors: [Object]
    }
```

Can someone help me with this issue?

**Comment by chybisov** [comment]
Hey, you are trying to send tokens to a contract address, not a wallet, so there is a limited number of bridges that can support this operation and sometimes they don't respond fast enough to return you a quote. You can try to use https://apidocs.li.fi/reference/post_quote-contractcalls endpoint for deposit to a contract.

We also return a reason why you didn't get a quote: 

```json
"errors":{"filteredOut":[{"reason":"Across does not send native ETH to contracts"}
```
