### ISSUE TITLE
How can i get transactionRequest that given route from over API

### ISSUE THREAD

**Issue by yulafezmesi** [lifinance/sdk#187]
hey, i believe `v1/quote `returns best route and returns `transactionRequest` inside of it. however, how can get `transactionRequest` that given route?

for instance, i fetched all routes over this `/advanced/routes` and want to get `transactionRequest` for second route. how can i achieve that?

thanks.

**Comment by chybisov** [comment]
@yulafezmesi Hey, each route contains a steps array, and you can get `transactionRequest` for each step using the `getStepTransaction` method.
