### ISSUE TITLE
ValidationError - The from amount must be greater than zero when using toAmount

### ISSUE THREAD

**Issue by dieguezguille** [lifinance/sdk#226]
As the title says, there seems to be a validation error when using `toAmount` in the `getContractCallsQuote` function. It will allow passing only a `fromAmount` but will complain if using only `toAmount`.

The error occurs in LI.FI SDK version: 3.5.0-beta.0 and the previous 3.4.2 version as well.

The printed error: 

`LiFi error: [SDKError: [HTTPError] [ValidationError] Request failed with status code 400. The from amount must be greater than zero. `

**Comment by chybisov** [comment]
@dieguezguille Hey, could you please share the full set of parameters you pass to the `getContractCallsQuote`?

**Comment by chybisov** [comment]
Hey, it should be fixed on production with a different error message.
