### ISSUE TITLE
CORS error when calling getPossibilities

### ISSUE THREAD

**Issue by etrpekson99** [lifinance/sdk#72]
I'm trying to upgrade the LiFi SDK version in a React project from **0.4.2** to the latest version **1.0.0-beta.6**.

I'm trying to use the `getPossibilities()` method but it's throwing the following error:
![Screen Shot 2022-05-25 at 10 26 54 PM](https://user-images.githubusercontent.com/39891505/170301429-5c0ea734-091a-4641-b4d4-41dec81ed91a.png)

Checking the network tab:
![Screen Shot 2022-05-25 at 10 27 44 PM](https://user-images.githubusercontent.com/39891505/170301918-f27a9003-28a1-4e7b-a01e-c9c1ceefd3df.png)

The config is set up like this:
```
const config = {
    rpcs: getRpcs(),
    defaultRouteOptions: {
      integrator: 'li.finance',
  },
};
const lifi = new LiFi(config);
```
and simply calling `getPossibilities` in a try-catch like this:
```
try {
  const possibilities = await lifi.getPossibilities();
} catch {
  (...)
}
```
Has anyone else encountered this problem? Would appreciate some help or support. Thanks

**Comment by chybisov** [comment]
@etrpekson99 [HTTP 429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) means you have made too many requests and exceeded the limit. Please try to wait several minutes and retry. 

P.S. We added a bunch of new, more granular endpoints in the latest version in addition to the `getPossibilities`: `getTokens`, `getChains`, `getTools`. We still need to update the documentation, but depending on your needs, you may benefit from using them already, and we consider them a primary way of fetching data.

**Comment by etrpekson99** [comment]
closing this since I have found the issue on my end, thanks a bunch for the help @chybisov
