### ISSUE TITLE
Add support for Candle

### ISSUE THREAD

**Issue by samisbakedham** [lifinance/sdk#73]
Candle is an EVM-compatible chain, L1.

**Comment by maxklenk** [comment]
Thank you for reaching out to us.
To add a new chain there has to be a bridge to that chain already. We can then aggregate that bridge and add the chain.
We are not planning to add Candle anytime soon, based on its explorer not a lot is happening on that chain: https://candleexplorer.com/txs

You can find a list of all chains we support and plan to support here:
https://docs.li.fi/products/supported-chains-bridges-and-exchanges

**Comment by samisbakedham** [comment]
> Thank you for reaching out to us.
> 
> To add a new chain there has to be a bridge to that chain already. We can then aggregate that bridge and add the chain.
> 
> We are not planning to add Candle anytime soon, based on its explorer not a lot is happening on that chain: https://candleexplorer.com/txs
> 
> 
> 
> You can find a list of all chains we support and plan to support here:
> 
> https://docs.li.fi/products/supported-chains-bridges-and-exchanges
> 
> 

Perceptions can be deceiving
